### ISSUE TITLE
NullReferenceException On v2.10.1

### ISSUE THREAD

**Issue by DanielSCBO** [enisn/UraniumUI#786]
Hello after update i got NullReferenceException the stack is

```
   at UraniumUI.Material.Controls.TextField.<>c.<.cctor>b__123_1(BindableObject bindable, Object oldValue, Object newValue) in C:\P\UraniumUI\src\UraniumUI.Material\Controls\TextField.BindableProperties.cs:line 42
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in /_/src/Controls/src/Core/BindableObject.cs:line 662
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindableObject.cs:line 587
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindableObject.cs:line 521
   at Microsoft.Maui.Controls.Setter.Apply(BindableObject target, SetterSpecificity specificity) in /_/src/Controls/src/Core/Setter.cs:line 81
   at Microsoft.Maui.Controls.Style.ApplyCore(BindableObject bindable, Style basedOn, SetterSpecificity specificity) in /_/src/Controls/src/Core/Style.cs:line 176
   at Microsoft.Maui.Controls.Style.Microsoft.Maui.Controls.IStyle.Apply(BindableObject bindable, SetterSpecificity specificity) in /_/src/Controls/src/Core/Style.cs:line 107
   at Microsoft.Maui.Controls.MergedStyle.SetStyle(IStyle implicitStyle, IList`1 classStyles, IStyle style) in /_/src/Controls/src/Core/MergedStyle.cs:line 203
   at Microsoft.Maui.Controls.MergedStyle.set_ImplicitStyle(IStyle value) in /_/src/Controls/src/Core/MergedStyle.cs:line 93
   at Microsoft.Maui.Controls.MergedStyle.OnImplicitStyleChanged() in /_/src/Controls/src/Core/MergedStyle.cs:line 140
   at Microsoft.Maui.Controls.MergedStyle.<RegisterImplicitStyles>b__31_0(BindableObject bindable, Object oldvalue, Object newvalue) in /_/src/Controls/src/Core/MergedStyle.cs:line 156
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in /_/src/Controls/src/Core/BindableObject.cs:line 662
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindableObject.cs:line 587
   at Microsoft.Maui.Controls.Element.OnResourceChanged(BindableProperty property, Object value, SetterSpecificity specificity) in /_/src/Controls/src/Core/Element/Element.cs:line 880
   at Microsoft.Maui.Controls.Element.OnSetDynamicResource(BindableProperty property, String key, SetterSpecificity specificity) in /_/src/Controls/src/Core/Element/Element.cs:line 753
   at Microsoft.Maui.Controls.BindableObject.SetDynamicResource(BindableProperty property, String key, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindableObject.cs:line 467
   at Microsoft.Maui.Controls.BindableObject.SetDynamicResource(BindableProperty property, String key) in /_/src/Controls/src/Core/BindableObject.cs:line 457
   at Microsoft.Maui.Controls.MergedStyle.RegisterImplicitStyles() in /_/src/Controls/src/Core/MergedStyle.cs:line 158
   at Microsoft.Maui.Controls.MergedStyle..ctor(Type targetType, BindableObject target) in /_/src/Controls/src/Core/MergedStyle.cs:line 33
   at Microsoft.Maui.Controls.NavigableElement..ctor() in /_/src/Controls/src/Core/Shell/NavigableElement.cs:line 29
   at Microsoft.Maui.Controls.VisualElement..ctor() in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 517
   at Microsoft.Maui.Controls.View..ctor() in /_/src/Controls/src/Core/View/View.cs:line 94
   at Microsoft.Maui.Controls.Compatibility.Layout..ctor() in /_/src/Controls/src/Core/LegacyLayouts/Layout.cs:line 109
   at Microsoft.Maui.Controls.TemplatedView..ctor()
   at Microsoft.Maui.Controls.ContentView..ctor()
   at UraniumUI.Material.Controls.InputField..ctor() in C:\P\UraniumUI\src\UraniumUI.Material\Controls\InputField.cs:line 146
   at UraniumUI.Material.Controls.TextField..ctor() in C:\P\UraniumUI\src\UraniumUI.Material\Controls\TextField.cs:line 39
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

I got style

```
    <Style TargetType="UI:TextField" BaseResourceKey="InputFieldBaseStyle">
        <Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource Black}, Dark={StaticResource White}}" />
        <Setter Property="BackgroundColor" Value="Transparent" />
        <Setter Property="FontFamily" Value="{StaticResource DefaultFontFamily}"/>
        <Setter Property="BorderColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray500}}" />
    </Style>
```

My {StaticResource DefaultFontFamily}

`
<x:String x:Key="DefaultFontFamily">Roboto</x:String>

`    

If i comment style the program works without problem

**Comment by enisn** [comment]
Will be included in the next patch

**Comment by rdurfee** [comment]
This same exception happens if you specify FontSize in a style, in version 2.10.2.

**Comment by DanielSCBO** [comment]
> This same exception happens if you specify FontSize in a style, in version 2.10.2.

Yes, I have the same problem
